services:
  postgres:
    container_name: postgres
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: food_ordering_system
      PGDATA: /data/postgres
    volumes:
      - /Users/zikozee/docker_db/postgres_food_ordering_system:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    shm_size: '1g'
    #cause of error could not resize shared memory segment


volumes:
  postgres: