server:
  port: 8181


logging:
  level:
    com.food.ordering.system: DEBUG


order-service:
  payment-request-topic-name: payment-request
  payment-response-topic-name: payment-response
  restaurant-approval-request-topic-name: restaurant-approval-request
  restaurant-approval-response-topic-name: restaurant-approval-response


spring:
  jpa:
    # this will disable open session in view which forces the persistence context to stay open so that the view layer
    # can trigger the proxy initialization - which keeps database connection open for a long time, hence very bad effect
    # on database performance
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    # binary transfer -> data will be transferred from postgres driver to JDBC driver in binary form which is faster
    # hence eliminating the need for conversion from text representation to binary representation

    # reWriteBatchedInserts -> this will increase the Batch insert performance by rewriting the Batch to use
    # multi-values i.e single insert statement and  multiple values
    # instead of multiple insert statement and multiple values

    # stringtype=unspecified :: tells JDBC driver to set all strings untypes this prevents string checking on UUID type in postgres
    url: jdbc:postgresql://localhost:5432/food_ordering_system?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  # none: no compression, lowest CPU, highest network usage
  # gzip:
    #- Highest compression ratio (except zstd can often match/exceed it)
    #- Slow compression
    #- High CPU usage
    #- Best when network bandwidth is the bottleneck

  # snappy:
    # - Good balance of CPU, speed, and compression
    # - Fast compression/decompression
    # - Moderate network savings
    # - Good legacy default

  # lz4:
    # - Lower compression ratio
    # - Extremely fast compression/decompression
    # - Very low CPU overhead
    # - Best for low-latency, high-throughput applications

  # zstd:
    # - Excellent compression ratio (typically better than snappy/lz4, often comparable to or better than gzip)
    # - Fast compression and decompression
    # - Moderate CPU usage
    # - Best overall choice for most modern Kafka deployments
  compression-type: snappy
  # all - the KafkaProducer will wait for all brokers to acknowledge before confirming the produce operation
  # 1 - just one broker acknowledgement is enough
  # 0 - no broker needs to acknowledge
  acks: all
  # default
  batch-size: 16384
  # added extra to the batch-size
  batch-size-boost-factor: 100
  # this is used to delay the producer before sending the data (ms)
  # hence allows you to increase throughput on batchsize
  linger-ms: 5
  # the timeout from producer when no response come from broker
  request-timeout-ms: 60000
  # retries 5 times on the producer side in case of error
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  # remember Kafka offset is matched to a consumer group
  # hence new/previous consumer in the group read from latest and not from the beginning using this unique id
  # if the id is random, when you restart, all consumers will read from beginning hence not preferred
  payment-consumer-group-id: payment-topic-consumer
  restaurant-approval-consumer-group-id: restaurant-approval-topic-consumer
  # it helps to read from the beginning of the partition: preferred behaviour
  auto-offset-reset: earliest
  # this is necessary since we are using Avro data type, the value has to be true
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  # consumer reads in batches
  batch-listener: true
  # to ensure Kafka start reading on start up
  auto-startup: true
  # remember 3 partitions means max of 3 consumers (if you create more consumers it will be idle until you add partitions to match)
  # if you say 3 brokers and 4 instances of the app, it means you will have a total of 9 partitions (3 partitions * 3 brokers)
  # and since you set 3 as the concurrency-level that would equal 12 consumer threads (concurrency-level * instances)
  # hence 3 consumer threads will be idle since 9 consumer threads alone will be active
  concurrency-level: 3
  # timeout to get at least 1 heart beat from a consumer, if broker does not get the consumer,
  # it marks the consumer as dead and remove it from the consumer group
  session-timeout-ms: 10000
  # the time interval in which the consumer send a heart beat signal to the broker
  # note it is set as 1/3 of session-timeout-ms - this is so to allow for considerable network failure
  # so it will try 3 times before timing out and the broker removes the consumer from the consumer group
  heartbeat-interval-ms: 3000
  # this should be set while putting our application logic processing time in perspective
  # if too short it means our logic may take more than the interval, hence coordinator will mark the consumer as dead
  # hence consumer is removed from group and consumer coordinator will trigger a new round of rebalance to assign to other consumbers
  max-poll-interval-ms: 300000
  # the max record the consumer can fetch for each poll
  max-poll-records: 500
  # though the max-poll-records is set to 500,
  # max-partition-fetch-bytes-default ensures the number of records does not exceed the max bytes set
  max-partition-fetch-bytes-default: 1048576
  # helper multiplier to increase the max-partition-fetch-bytes-default id required
  max-partition-fetch-bytes-boost-factor: 1
  # consumer wait time before polling again, should not be too small (more cpu resources),
  # if too large your code will be blocked instead of doing real work
  poll-timeout-ms: 150